# Generated by Django 5.2.16 on 2026-08-16 09:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_pool_type_customer_quote_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('company_snapshot', models.CharField(max_length=128, verbose_name='客户公司名称')),
                ('contact_name_snapshot', models.CharField(max_length=32, verbose_name='联系人')),
                ('phone_snapshot', models.CharField(max_length=32, verbose_name='联系方式')),
                ('source_snapshot', models.CharField(blank=True, max_length=64, verbose_name='客户来源')),
                ('quote_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='报价金额')),
                ('deal_business', models.CharField(blank=True, max_length=128, verbose_name='成交业务')),
                ('contract_entity', models.CharField(blank=True, max_length=128, verbose_name='签约主体')),
                ('is_invoiced', models.BooleanField(default=False, verbose_name='是否开票')),
                ('is_tax_included', models.BooleanField(default=False, verbose_name='是否含税')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='录入时间')),
                ('deal_at', models.DateTimeField(blank=True, editable=False, verbose_name='成交时间')),
                ('site_category', models.CharField(blank=True, max_length=64, verbose_name='网站搭建类目')),
                ('site_info', models.TextField(blank=True, verbose_name='网站搭建信息')),
                ('site_progress', models.CharField(choices=[('not_started', '待开始'), ('in_progress', '进行中'), ('done', '已完成')], default='not_started', max_length=16, verbose_name='网站搭建进度')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('consultant', models.ForeignKey(blank=True, db_constraint=False, help_text='成交时为空，由咨询主管（嘉茵）或总经办分配后填入', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='咨询师')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer', verbose_name='客户')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sales', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='销售人员')),
            ],
            options={
                'verbose_name': 'historical 成交项目',
                'verbose_name_plural': 'historical 成交项目',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_snapshot', models.CharField(max_length=128, verbose_name='客户公司名称')),
                ('contact_name_snapshot', models.CharField(max_length=32, verbose_name='联系人')),
                ('phone_snapshot', models.CharField(max_length=32, verbose_name='联系方式')),
                ('source_snapshot', models.CharField(blank=True, max_length=64, verbose_name='客户来源')),
                ('quote_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='报价金额')),
                ('deal_business', models.CharField(blank=True, max_length=128, verbose_name='成交业务')),
                ('contract_entity', models.CharField(blank=True, max_length=128, verbose_name='签约主体')),
                ('is_invoiced', models.BooleanField(default=False, verbose_name='是否开票')),
                ('is_tax_included', models.BooleanField(default=False, verbose_name='是否含税')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('deal_at', models.DateTimeField(auto_now_add=True, verbose_name='成交时间')),
                ('site_category', models.CharField(blank=True, max_length=64, verbose_name='网站搭建类目')),
                ('site_info', models.TextField(blank=True, verbose_name='网站搭建信息')),
                ('site_progress', models.CharField(choices=[('not_started', '待开始'), ('in_progress', '进行中'), ('done', '已完成')], default='not_started', max_length=16, verbose_name='网站搭建进度')),
                ('consultant', models.ForeignKey(blank=True, help_text='成交时为空，由咨询主管（嘉茵）或总经办分配后填入', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulting_projects', to=settings.AUTH_USER_MODEL, verbose_name='咨询师')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='customers.customer', verbose_name='客户')),
                ('sales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_projects', to=settings.AUTH_USER_MODEL, verbose_name='销售人员')),
            ],
            options={
                'verbose_name': '成交项目',
                'verbose_name_plural': '成交项目',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProjectPayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('note', models.CharField(blank=True, help_text="如'定金'/'尾款'", max_length=128, verbose_name='备注')),
                ('recorded_at', models.DateTimeField(blank=True, editable=False, verbose_name='填写时间')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='填写人（咨询师）')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': 'historical 项目收款记录',
                'verbose_name_plural': 'historical 项目收款记录',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProjectExpense',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('note', models.CharField(blank=True, help_text="如'域名费'/'服务器费'", max_length=128, verbose_name='备注')),
                ('recorded_at', models.DateTimeField(blank=True, editable=False, verbose_name='填写时间')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='填写人（咨询师）')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': 'historical 项目支出记录',
                'verbose_name_plural': 'historical 项目支出记录',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProjectConsultantHistory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('seq', models.PositiveSmallIntegerField(default=1, verbose_name='第几次分配')),
                ('assigned_at', models.DateTimeField(blank=True, editable=False, verbose_name='分配时间')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='分配人（嘉茵/总经办）')),
                ('from_consultant', models.ForeignKey(blank=True, db_constraint=False, help_text='为空表示首次分配', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='上一任咨询师')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_consultant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='本次咨询师')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': 'historical 咨询师分配历史',
                'verbose_name_plural': 'historical 咨询师分配历史',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_attachments/%Y/%m/', verbose_name='附图')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.project', verbose_name='项目')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '项目附图',
                'verbose_name_plural': '项目附图',
            },
        ),
        migrations.CreateModel(
            name='ProjectConsultantHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveSmallIntegerField(default=1, verbose_name='第几次分配')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='分配人（嘉茵/总经办）')),
                ('from_consultant', models.ForeignKey(blank=True, help_text='为空表示首次分配', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='上一任咨询师')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_history', to='projects.project', verbose_name='项目')),
                ('to_consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='本次咨询师')),
            ],
            options={
                'verbose_name': '咨询师分配历史',
                'verbose_name_plural': '咨询师分配历史',
                'ordering': ['project_id', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('note', models.CharField(blank=True, help_text="如'域名费'/'服务器费'", max_length=128, verbose_name='备注')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='填写时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project', verbose_name='项目')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='填写人（咨询师）')),
            ],
            options={
                'verbose_name': '项目支出记录',
                'verbose_name_plural': '项目支出记录',
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('note', models.CharField(blank=True, help_text="如'定金'/'尾款'", max_length=128, verbose_name='备注')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='填写时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.project', verbose_name='项目')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='填写人（咨询师）')),
            ],
            options={
                'verbose_name': '项目收款记录',
                'verbose_name_plural': '项目收款记录',
                'ordering': ['recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['sales'], name='projects_pr_sales_i_946b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['consultant'], name='projects_pr_consult_af4d49_idx'),
        ),
    ]
