# Generated by Django 5.2.16 on 2026-08-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_historicalproject_tech_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='site_category',
            field=models.CharField(blank=True, choices=[('ICP', 'ICP许可证'), ('EDI', 'EDI许可证'), ('ICPEDI', 'ICPEDI（组合套餐）'), ('corp_site', '企业官网'), ('corp_site_icp', '企业官网+备案'), ('app', 'APP/小程序'), ('other', '其他')], help_text='选择建站类型(如 ICPEDI/企业官网+备案),咨询师填写', max_length=64, verbose_name='网站搭建类目'),
        ),
        migrations.AlterField(
            model_name='project',
            name='site_category',
            field=models.CharField(blank=True, choices=[('ICP', 'ICP许可证'), ('EDI', 'EDI许可证'), ('ICPEDI', 'ICPEDI（组合套餐）'), ('corp_site', '企业官网'), ('corp_site_icp', '企业官网+备案'), ('app', 'APP/小程序'), ('other', '其他')], help_text='选择建站类型(如 ICPEDI/企业官网+备案),咨询师填写', max_length=64, verbose_name='网站搭建类目'),
        ),
    ]
