# Generated by Django 5.2.16 on 2026-08-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_historicalproject_site_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='site_contact_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='网站联系地址'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='site_contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='网站联系邮箱'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='site_contact_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='网站联系电话'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='site_domain',
            field=models.CharField(blank=True, max_length=128, verbose_name='域名'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='site_full_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='网站全称'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='site_icp_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='备案号'),
        ),
        migrations.AddField(
            model_name='project',
            name='site_contact_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='网站联系地址'),
        ),
        migrations.AddField(
            model_name='project',
            name='site_contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='网站联系邮箱'),
        ),
        migrations.AddField(
            model_name='project',
            name='site_contact_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='网站联系电话'),
        ),
        migrations.AddField(
            model_name='project',
            name='site_domain',
            field=models.CharField(blank=True, max_length=128, verbose_name='域名'),
        ),
        migrations.AddField(
            model_name='project',
            name='site_full_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='网站全称'),
        ),
        migrations.AddField(
            model_name='project',
            name='site_icp_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='备案号'),
        ),
    ]
