# Generated by Django 5.2.16 on 2026-08-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_historicalproject_site_contact_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='site_category',
            field=models.CharField(blank=True, choices=[('ICP', 'ICP许可证'), ('EDI', 'EDI许可证'), ('ICPEDI', 'ICPEDI（组合套餐）'), ('corp_site', '企业官网'), ('corp_site_icp', '企业官网+备案'), ('app', 'APP/小程序'), ('other', '其他')], help_text="由成交业务自动带出(如成交业务'ICPEDI 双证办理'→类目ICPEDI),无需手动选择", max_length=64, verbose_name='网站搭建类目'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='site_domain',
            field=models.TextField(blank=True, help_text='支持多个域名,每行一个(如:abc.com / abc.top)', verbose_name='域名'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='site_icp_number',
            field=models.TextField(blank=True, help_text='支持多个备案号,每行一个,与域名对应(如:abc.com 对应 xxxx-1号)', verbose_name='备案号'),
        ),
        migrations.AlterField(
            model_name='project',
            name='site_category',
            field=models.CharField(blank=True, choices=[('ICP', 'ICP许可证'), ('EDI', 'EDI许可证'), ('ICPEDI', 'ICPEDI（组合套餐）'), ('corp_site', '企业官网'), ('corp_site_icp', '企业官网+备案'), ('app', 'APP/小程序'), ('other', '其他')], help_text="由成交业务自动带出(如成交业务'ICPEDI 双证办理'→类目ICPEDI),无需手动选择", max_length=64, verbose_name='网站搭建类目'),
        ),
        migrations.AlterField(
            model_name='project',
            name='site_domain',
            field=models.TextField(blank=True, help_text='支持多个域名,每行一个(如:abc.com / abc.top)', verbose_name='域名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='site_icp_number',
            field=models.TextField(blank=True, help_text='支持多个备案号,每行一个,与域名对应(如:abc.com 对应 xxxx-1号)', verbose_name='备案号'),
        ),
    ]
