# Generated by Django 5.2.16 on 2026-08-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_historicalproject_site_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='site_progress',
            field=models.CharField(choices=[('not_started', '待开始'), ('in_progress', '进行中'), ('completed_pending', '已完成待部署'), ('deployed', '已部署')], default='not_started', max_length=32, verbose_name='网站搭建进度'),
        ),
        migrations.AlterField(
            model_name='project',
            name='site_progress',
            field=models.CharField(choices=[('not_started', '待开始'), ('in_progress', '进行中'), ('completed_pending', '已完成待部署'), ('deployed', '已部署')], default='not_started', max_length=32, verbose_name='网站搭建进度'),
        ),
    ]
