# Generated by Django 5.2.16 on 2026-08-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_historicalproject_site_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='site_domain',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='site_icp_number',
        ),
        migrations.RemoveField(
            model_name='project',
            name='site_domain',
        ),
        migrations.RemoveField(
            model_name='project',
            name='site_icp_number',
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='site_domain_icp',
            field=models.TextField(blank=True, help_text='每行一个,格式:域名 备案号(如:a.com xxxx-1号 / b.com xxxx-2号)', verbose_name='域名与备案号'),
        ),
        migrations.AddField(
            model_name='project',
            name='site_domain_icp',
            field=models.TextField(blank=True, help_text='每行一个,格式:域名 备案号(如:a.com xxxx-1号 / b.com xxxx-2号)', verbose_name='域名与备案号'),
        ),
    ]
