# Generated by Django 5.2.16 on 2026-09-02

from django.db import migrations


def retire_dual_financials(apps, schema_editor):
    """一表化(老板 09-02 拍板):收款/支出唯一源=客户侧 Receipt/Cost.

    0021 迁移时把项目侧 Payment/Expense 复制到客户侧(原表保留),此后两边同源重复;
    本次删除项目侧重复数据(录入入口已随 ProjectAdmin 退役一并关闭),客户侧数据零改动.
    审计:历史表 HistoricalProjectPayment/Expense 照常留痕."""
    ProjectPayment = apps.get_model("projects", "ProjectPayment")
    ProjectExpense = apps.get_model("projects", "ProjectExpense")
    npay = ProjectPayment.objects.count()
    nexp = ProjectExpense.objects.count()
    ProjectPayment.objects.all().delete()
    ProjectExpense.objects.all().delete()
    print(f"[data-migration] 删除项目侧重复收款 {npay} 条 / 支出 {nexp} 条(客户 Receipt/Cost 唯一源保留)")


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_remove_historicalproject_site_domain_and_more"),
    ]

    operations = [
        migrations.RunPython(retire_dual_financials, migrations.RunPython.noop),
    ]
