# Generated by Django 5.2.16 on 2026-07-25 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(db_index=True, max_length=128, verbose_name='公司名称')),
                ('contact_name', models.CharField(max_length=32, verbose_name='对接人')),
                ('phone', models.CharField(db_index=True, max_length=32, verbose_name='联系电话')),
                ('qualification_interest', models.CharField(blank=True, max_length=128, verbose_name='需求资质')),
                ('source', models.CharField(choices=[('referral', '转介绍'), ('inbound', '主动咨询'), ('ad', '广告投放'), ('other', '其他')], default='other', max_length=16, verbose_name='来源')),
                ('note', models.TextField(blank=True, verbose_name='客户情况')),
                ('consulted_at', models.DateField(blank=True, null=True, verbose_name='咨询时间')),
                ('status', models.CharField(choices=[('lead', '线索'), ('following', '跟进中'), ('pool', '公海'), ('deal', '已成交'), ('lost', '已流失')], default='lead', max_length=16, verbose_name='状态')),
                ('pool_entered_at', models.DateTimeField(blank=True, null=True, verbose_name='进入公海时间')),
                ('last_follow_at', models.DateTimeField(blank=True, null=True, verbose_name='最近跟进时间')),
                ('lost_reason', models.CharField(blank=True, max_length=255, verbose_name='流失原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL, verbose_name='建档人')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='归属销售')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='跟进内容')),
                ('next_follow_at', models.DateTimeField(blank=True, null=True, verbose_name='下次跟进提醒')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='跟进时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='customers.customer', verbose_name='客户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='跟进人')),
            ],
            options={
                'verbose_name': '跟进记录',
                'verbose_name_plural': '跟进记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['status', 'owner'], name='customers_c_status_cb54aa_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_follow_at'], name='customers_c_last_fo_93b456_idx'),
        ),
    ]
