# Generated by Django 5.2.16 on 2026-08-16 09:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pool_type',
            field=models.CharField(blank=True, choices=[('auto', '自动掉入公海'), ('square', '客户池广场（手动释放）')], help_text='仅 status=pool 时有意义：区分自动掉入/客户池广场释放', max_length=16, null=True, verbose_name='公海类型'),
        ),
        migrations.AddField(
            model_name='customer',
            name='quote_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='v2 claim 新增：第一页客户信息字段', max_digits=12, null=True, verbose_name='报价金额'),
        ),
        migrations.AddField(
            model_name='customer',
            name='square_released_by',
            field=models.ForeignKey(blank=True, help_text="客户池广场来源署名用：来源栏展示'客户池广场-XX'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='square_released_customers', to=settings.AUTH_USER_MODEL, verbose_name='广场释放人'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='note',
            field=models.TextField(blank=True, verbose_name='客户情况/备注'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='qualification_interest',
            field=models.CharField(blank=True, choices=[('动漫网文', '动漫网文'), ('表演网文', '表演网文'), ('音乐网文', '音乐网文'), ('游戏文网文', '游戏文网文'), ('混合网文', '混合网文'), ('ICP许可证', 'ICP许可证'), ('EDI许可证', 'EDI许可证'), ('ICPEDI', 'ICPEDI（组合套餐）'), ('广播证', '广播电视节目制作经营许可证')], max_length=32, verbose_name='需求资质'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('referral', '转介绍'), ('inbound', '主动咨询'), ('ad', '广告投放'), ('square', '客户池广场'), ('other', '其他')], default='other', max_length=16, verbose_name='来源'),
        ),
        migrations.CreateModel(
            name='CustomerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='customer_attachments/%Y/%m/', verbose_name='附图')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='customers.customer', verbose_name='客户')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '客户附图',
                'verbose_name_plural': '客户附图',
            },
        ),
        migrations.CreateModel(
            name='CustomerOwnerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('direct_input', '销售直接建档'), ('square', '客户池广场获取'), ('manager_assign', '销售主管分配'), ('boss_assign', '总经办分配'), ('sales_claim', '销售自主领取（旧公海通道）')], max_length=20, verbose_name='来源类型')),
                ('source_note', models.CharField(blank=True, help_text='广场场景记录释放人姓名，分配场景记录操作人姓名', max_length=64, verbose_name='来源备注')),
                ('seq', models.PositiveSmallIntegerField(default=1, verbose_name='第几次流转')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='流转时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_history', to='customers.customer', verbose_name='客户')),
                ('from_user', models.ForeignKey(blank=True, help_text='为空表示这是栈底（首次建档/首次分配）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='上一持有人')),
                ('operator', models.ForeignKey(help_text='谁触发的这次流转（主管/总经办/销售本人）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='本次持有人')),
            ],
            options={
                'verbose_name': '客户归属变更历史',
                'verbose_name_plural': '客户归属变更历史',
                'ordering': ['customer_id', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCustomer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('company', models.CharField(db_index=True, max_length=128, verbose_name='公司名称')),
                ('contact_name', models.CharField(max_length=32, verbose_name='对接人')),
                ('phone', models.CharField(db_index=True, max_length=32, verbose_name='联系电话')),
                ('qualification_interest', models.CharField(blank=True, choices=[('动漫网文', '动漫网文'), ('表演网文', '表演网文'), ('音乐网文', '音乐网文'), ('游戏文网文', '游戏文网文'), ('混合网文', '混合网文'), ('ICP许可证', 'ICP许可证'), ('EDI许可证', 'EDI许可证'), ('ICPEDI', 'ICPEDI（组合套餐）'), ('广播证', '广播电视节目制作经营许可证')], max_length=32, verbose_name='需求资质')),
                ('source', models.CharField(choices=[('referral', '转介绍'), ('inbound', '主动咨询'), ('ad', '广告投放'), ('square', '客户池广场'), ('other', '其他')], default='other', max_length=16, verbose_name='来源')),
                ('quote_amount', models.DecimalField(blank=True, decimal_places=2, help_text='v2 claim 新增：第一页客户信息字段', max_digits=12, null=True, verbose_name='报价金额')),
                ('note', models.TextField(blank=True, verbose_name='客户情况/备注')),
                ('consulted_at', models.DateField(blank=True, null=True, verbose_name='咨询时间')),
                ('status', models.CharField(choices=[('lead', '线索'), ('following', '跟进中'), ('pool', '公海'), ('deal', '已成交'), ('lost', '已流失')], default='lead', max_length=16, verbose_name='状态')),
                ('pool_type', models.CharField(blank=True, choices=[('auto', '自动掉入公海'), ('square', '客户池广场（手动释放）')], help_text='仅 status=pool 时有意义：区分自动掉入/客户池广场释放', max_length=16, null=True, verbose_name='公海类型')),
                ('pool_entered_at', models.DateTimeField(blank=True, null=True, verbose_name='进入公海时间')),
                ('last_follow_at', models.DateTimeField(blank=True, null=True, verbose_name='最近跟进时间')),
                ('lost_reason', models.CharField(blank=True, max_length=255, verbose_name='流失原因')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='建档人')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='归属销售')),
                ('square_released_by', models.ForeignKey(blank=True, db_constraint=False, help_text="客户池广场来源署名用：来源栏展示'客户池广场-XX'", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='广场释放人')),
            ],
            options={
                'verbose_name': 'historical 客户',
                'verbose_name_plural': 'historical 客户',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCustomerOwnerHistory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('direct_input', '销售直接建档'), ('square', '客户池广场获取'), ('manager_assign', '销售主管分配'), ('boss_assign', '总经办分配'), ('sales_claim', '销售自主领取（旧公海通道）')], max_length=20, verbose_name='来源类型')),
                ('source_note', models.CharField(blank=True, help_text='广场场景记录释放人姓名，分配场景记录操作人姓名', max_length=64, verbose_name='来源备注')),
                ('seq', models.PositiveSmallIntegerField(default=1, verbose_name='第几次流转')),
                ('assigned_at', models.DateTimeField(blank=True, editable=False, verbose_name='流转时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer', verbose_name='客户')),
                ('from_user', models.ForeignKey(blank=True, db_constraint=False, help_text='为空表示这是栈底（首次建档/首次分配）', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='上一持有人')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, db_constraint=False, help_text='谁触发的这次流转（主管/总经办/销售本人）', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('to_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='本次持有人')),
            ],
            options={
                'verbose_name': 'historical 客户归属变更历史',
                'verbose_name_plural': 'historical 客户归属变更历史',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
