# Generated by Django 5.2.16 on 2026-08-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_pool_type_customer_quote_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycledCustomer',
            fields=[
            ],
            options={
                'verbose_name': '回收站客户',
                'verbose_name_plural': '回收站（已删除客户）',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customers.customer',),
        ),
        migrations.AddField(
            model_name='customer',
            name='duplicate_flagged_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='细则第一页·六：录入时与其他同事客户疑似重复，已做标识待总经办核查', null=True, verbose_name='撞单标识时间'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='duplicate_flagged_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='细则第一页·六：录入时与其他同事客户疑似重复，已做标识待总经办核查', null=True, verbose_name='撞单标识时间'),
        ),
        migrations.AlterField(
            model_name='customerownerhistory',
            name='source_type',
            field=models.CharField(choices=[('direct_input', '销售直接建档'), ('square', '客户池广场获取'), ('manager_assign', '销售主管分配'), ('boss_assign', '总经办分配'), ('sales_claim', '销售自主领取（旧公海通道）'), ('auto_pool', '30天未跟进自动掉入公海')], max_length=20, verbose_name='来源类型'),
        ),
        migrations.AlterField(
            model_name='historicalcustomerownerhistory',
            name='source_type',
            field=models.CharField(choices=[('direct_input', '销售直接建档'), ('square', '客户池广场获取'), ('manager_assign', '销售主管分配'), ('boss_assign', '总经办分配'), ('sales_claim', '销售自主领取（旧公海通道）'), ('auto_pool', '30天未跟进自动掉入公海')], max_length=20, verbose_name='来源类型'),
        ),
    ]
