# Generated by Django 5.2.16 on 2026-08-16 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_repair_square_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='跟进时间'),
        ),
    ]
