# Generated by Django 5.2.16 on 2026-08-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_followup_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='duplicate_flagged_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='疑似重复已标识', null=True, verbose_name='撞单标识时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pool_type',
            field=models.CharField(blank=True, choices=[('auto', '自动掉入公海'), ('square', '客户池广场（手动释放）')], help_text='自动掉入/广场释放', max_length=16, null=True, verbose_name='公海类型'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='duplicate_flagged_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='疑似重复已标识', null=True, verbose_name='撞单标识时间'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='pool_type',
            field=models.CharField(blank=True, choices=[('auto', '自动掉入公海'), ('square', '客户池广场（手动释放）')], help_text='自动掉入/广场释放', max_length=16, null=True, verbose_name='公海类型'),
        ),
    ]
