# Generated by Django 5.2.16 on 2026-08-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_duplicate_flagged_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pool_type',
            field=models.CharField(blank=True, choices=[('auto', '自动掉入公海'), ('square', '客户池广场（手动释放）')], help_text='30天未跟进自动进公海，或销售手动释放到客户池广场', max_length=16, null=True, verbose_name='公海类型'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='pool_type',
            field=models.CharField(blank=True, choices=[('auto', '自动掉入公海'), ('square', '客户池广场（手动释放）')], help_text='30天未跟进自动进公海，或销售手动释放到客户池广场', max_length=16, null=True, verbose_name='公海类型'),
        ),
    ]
