# Generated by Django 5.2.16 on 2026-08-17 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_pool_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='quote_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='报价金额'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='square_released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='square_released_customers', to=settings.AUTH_USER_MODEL, verbose_name='广场释放人'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='quote_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='报价金额'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='square_released_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='广场释放人'),
        ),
    ]
