# Generated by Django 5.2.16 on 2026-08-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_quote_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='qualification_interest',
            field=models.JSONField(blank=True, default=list, help_text='客户可同时咨询多个资质,如 ICP + EDI', verbose_name='需求资质(可多选)'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='qualification_interest',
            field=models.JSONField(blank=True, default=list, help_text='客户可同时咨询多个资质,如 ICP + EDI', verbose_name='需求资质(可多选)'),
        ),
    ]
