# Generated by Django 5.2.16 on 2026-08-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_customer_qualification_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_name',
            field=models.CharField(max_length=32, verbose_name='客户联系人'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='contact_name',
            field=models.CharField(max_length=32, verbose_name='客户联系人'),
        ),
    ]
