# Generated by Django 5.2.16 on 2026-08-20 04:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_customer_contact_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='提交', max_length=32, verbose_name='动作')),
                ('target', models.CharField(blank=True, max_length=200, verbose_name='对象')),
                ('detail', models.TextField(blank=True, verbose_name='提交信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '提交日志',
                'verbose_name_plural': '提交日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
