# Generated by Django 5.2.16 on 2026-08-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_visitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='ip',
            field=models.CharField(blank=True, max_length=64, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='visitlog',
            name='method',
            field=models.CharField(blank=True, max_length=10, verbose_name='方法'),
        ),
        migrations.AddField(
            model_name='visitlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, verbose_name='设备/浏览器'),
        ),
    ]
