# Generated by Django 5.2.16 on 2026-08-28 08:46

from django.db import migrations, models


def backfill_deal_status(apps, schema_editor):
    """存量已成交客户回填成交状态为 进行中(active)."""
    Customer = apps.get_model("customers", "Customer")
    Customer.objects.filter(status="deal", deal_status__isnull=True).update(deal_status="active")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_visitlog_ip_visitlog_method_visitlog_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deal_status',
            field=models.CharField(blank=True, choices=[('active', '进行中'), ('done', '已完结'), ('on_hold', '搁置')], help_text='仅 status=deal 时有效:进行中(active)/已完结(done)/搁置(on_hold)', max_length=16, null=True, verbose_name='成交状态'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='deal_status',
            field=models.CharField(blank=True, choices=[('active', '进行中'), ('done', '已完结'), ('on_hold', '搁置')], help_text='仅 status=deal 时有效:进行中(active)/已完结(done)/搁置(on_hold)', max_length=16, null=True, verbose_name='成交状态'),
        ),
        migrations.RunPython(backfill_deal_status, noop),
    ]
