# Generated by Django 5.2.16 on 2026-08-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_customer_deal_status_historicalcustomer_deal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerownerhistory',
            name='source_type',
            field=models.CharField(choices=[('direct_input', '销售直接建档'), ('square', '客户池广场获取'), ('manager_assign', '销售主管分配'), ('boss_assign', '总经办分配'), ('sales_claim', '销售自主领取（旧公海通道）'), ('auto_pool', '30天未跟进自动掉入公海'), ('deal_back_my', '成交转回我的客户'), ('deal_back_pool', '成交转回公司客户池')], max_length=20, verbose_name='来源类型'),
        ),
        migrations.AlterField(
            model_name='historicalcustomerownerhistory',
            name='source_type',
            field=models.CharField(choices=[('direct_input', '销售直接建档'), ('square', '客户池广场获取'), ('manager_assign', '销售主管分配'), ('boss_assign', '总经办分配'), ('sales_claim', '销售自主领取（旧公海通道）'), ('auto_pool', '30天未跟进自动掉入公海'), ('deal_back_my', '成交转回我的客户'), ('deal_back_pool', '成交转回公司客户池')], max_length=20, verbose_name='来源类型'),
        ),
    ]
