# Generated by Django 5.2.16 on 2026-08-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_alter_customerownerhistory_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='intention',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], null=True, verbose_name='客户意向(1-5星)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='qq',
            field=models.CharField(blank=True, max_length=32, verbose_name='QQ号'),
        ),
        migrations.AddField(
            model_name='customer',
            name='wechat',
            field=models.CharField(blank=True, max_length=64, verbose_name='微信号'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='intention',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], null=True, verbose_name='客户意向(1-5星)'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='qq',
            field=models.CharField(blank=True, max_length=32, verbose_name='QQ号'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='wechat',
            field=models.CharField(blank=True, max_length=64, verbose_name='微信号'),
        ),
    ]
