# Generated by Django 5.2.16 on 2026-08-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_customer_intention_customer_qq_customer_wechat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(default='other', max_length=32, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='source',
            field=models.CharField(default='other', max_length=32, verbose_name='来源'),
        ),
    ]
