# Generated by Django 5.2.16 on 2026-08-28 10:58

from django.db import migrations, models


def map_legacy_sources_to_labels(apps, schema_editor):
    """来源改为自由文本后,存量英文枚举值迁移为中文标签(square 保留,客户池广场署名逻辑依赖)."""
    Customer = apps.get_model("customers", "Customer")
    mapping = {"referral": "转介绍", "inbound": "主动咨询", "ad": "广告投放", "other": "其他"}
    for old, new in mapping.items():
        Customer.objects.filter(source=old).update(source=new)


def reverse_mapping(apps, schema_editor):
    Customer = apps.get_model("customers", "Customer")
    mapping = {"转介绍": "referral", "主动咨询": "inbound", "广告投放": "ad", "其他": "other"}
    for label, old in mapping.items():
        Customer.objects.filter(source=label).update(source=old)


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_alter_customer_source_and_more'),
    ]

    operations = [
        migrations.RunPython(map_legacy_sources_to_labels, reverse_mapping),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(default='其他', max_length=32, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='source',
            field=models.CharField(default='其他', max_length=32, verbose_name='来源'),
        ),
    ]
