# Generated by Django 5.2.16 on 2026-09-01 10:35

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_alter_customer_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='支出金额')),
                ('category', models.CharField(choices=[('domain', '域名'), ('server', '服务器'), ('tech', '技术费'), ('misc', '杂费'), ('other', '其他')], default='other', max_length=16, verbose_name='成本类型')),
                ('note', models.CharField(blank=True, help_text="如'域名费'/'服务器费'/'技术费'", max_length=128, verbose_name='备注')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=16, verbose_name='审核状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='customers.customer', verbose_name='成交客户')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_costs', to=settings.AUTH_USER_MODEL, verbose_name='申请/填写人(咨询师)')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_costs', to=settings.AUTH_USER_MODEL, verbose_name='审核人(总经办)')),
            ],
            options={
                'verbose_name': '支出记录',
                'verbose_name_plural': '支出记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCost',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='支出金额')),
                ('category', models.CharField(choices=[('domain', '域名'), ('server', '服务器'), ('tech', '技术费'), ('misc', '杂费'), ('other', '其他')], default='other', max_length=16, verbose_name='成本类型')),
                ('note', models.CharField(blank=True, help_text="如'域名费'/'服务器费'/'技术费'", max_length=128, verbose_name='备注')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=16, verbose_name='审核状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='申请时间')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer', verbose_name='成交客户')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='申请/填写人(咨询师)')),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='审核人(总经办)')),
            ],
            options={
                'verbose_name': 'historical 支出记录',
                'verbose_name_plural': 'historical 支出记录',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReceipt',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='收款金额')),
                ('note', models.CharField(blank=True, help_text="如'定金'/'尾款'/'全款'", max_length=128, verbose_name='备注')),
                ('received_at', models.DateField(blank=True, help_text='实际到账日期', null=True, verbose_name='收款时间')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='录入时间')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer', verbose_name='成交客户')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='填写人(咨询师)')),
            ],
            options={
                'verbose_name': 'historical 收款记录',
                'verbose_name_plural': 'historical 收款记录',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='收款金额')),
                ('note', models.CharField(blank=True, help_text="如'定金'/'尾款'/'全款'", max_length=128, verbose_name='备注')),
                ('received_at', models.DateField(blank=True, help_text='实际到账日期', null=True, verbose_name='收款时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='customers.customer', verbose_name='成交客户')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_receipts', to=settings.AUTH_USER_MODEL, verbose_name='填写人(咨询师)')),
            ],
            options={
                'verbose_name': '收款记录',
                'verbose_name_plural': '收款记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
