# Generated by Django 5.2.16 on 2026-09-01 10:38

from django.db import migrations


def migrate_project_financials(apps, schema_editor):
    """成交项目并入成交客户(老板拍板 09-01):项目财务记录迁移到成交客户,零丢失.

    收款 ProjectPayment → Receipt(挂成交客户);支出 ProjectExpense → Cost(历史支出已实际发生,直接计入成本).
    """
    Receipt = apps.get_model("customers", "Receipt")
    Cost = apps.get_model("customers", "Cost")
    ProjectPayment = apps.get_model("projects", "ProjectPayment")
    ProjectExpense = apps.get_model("projects", "ProjectExpense")

    n_r = n_c = 0
    for pp in ProjectPayment.objects.all().select_related("project", "recorded_by"):
        if pp.project_id and pp.project.customer_id:
            Receipt.objects.create(
                customer_id=pp.project.customer_id,
                amount=pp.amount,
                note=pp.note or "",
                recorded_by=pp.recorded_by,
                received_at=pp.recorded_at.date() if pp.recorded_at else None,
            )
            n_r += 1
    for pe in ProjectExpense.objects.all().select_related("project", "recorded_by"):
        if pe.project_id and pe.project.customer_id:
            Cost.objects.create(
                customer_id=pe.project.customer_id,
                amount=pe.amount,
                note=pe.note or "",
                recorded_by=pe.recorded_by,
                status="approved",  # 历史支出已实际发生,直接计入成本
            )
            n_c += 1
    print(f"[data-migration] 收款 {n_r} 条 → Receipt, 支出 {n_c} 条 → Cost")


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_cost_historicalcost_historicalreceipt_receipt'),
        ('projects', '0007_remove_historicalproject_site_domain_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_project_financials, migrations.RunPython.noop),
    ]
