# Generated by Django 5.2.16 on 2026-09-02 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_migrate_project_financials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_consultant_customers', to=settings.AUTH_USER_MODEL, verbose_name='咨询师'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contract_entity',
            field=models.CharField(blank=True, help_text='成交时确定的合同签约主体(一般=公司名)', max_length=128, verbose_name='签约主体'),
        ),
        migrations.AddField(
            model_name='customer',
            name='deal_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='成交时间'),
        ),
        migrations.AddField(
            model_name='customer',
            name='deal_business',
            field=models.CharField(blank=True, max_length=128, verbose_name='成交业务'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_invoiced',
            field=models.BooleanField(default=False, verbose_name='是否开票'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_tax_included',
            field=models.BooleanField(default=False, verbose_name='是否含税'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_sales_customers', to=settings.AUTH_USER_MODEL, verbose_name='成交销售'),
        ),
        migrations.AddField(
            model_name='customer',
            name='site_category',
            field=models.CharField(blank=True, choices=[('ICP', 'ICP许可证'), ('EDI', 'EDI许可证'), ('ICPEDI', 'ICPEDI（组合套餐）'), ('corp_site', '企业官网'), ('corp_site_icp', '企业官网+备案'), ('app', 'APP/小程序'), ('other', '其他')], max_length=24, verbose_name='建站类目'),
        ),
        migrations.AddField(
            model_name='customer',
            name='site_contact_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='网站联系地址'),
        ),
        migrations.AddField(
            model_name='customer',
            name='site_contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='网站联系邮箱'),
        ),
        migrations.AddField(
            model_name='customer',
            name='site_contact_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='网站联系电话'),
        ),
        migrations.AddField(
            model_name='customer',
            name='site_domain_icp',
            field=models.TextField(blank=True, verbose_name='域名与备案'),
        ),
        migrations.AddField(
            model_name='customer',
            name='site_full_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='网站全称'),
        ),
        migrations.AddField(
            model_name='customer',
            name='site_info',
            field=models.TextField(blank=True, verbose_name='网站搭建信息'),
        ),
        migrations.AddField(
            model_name='customer',
            name='site_progress',
            field=models.CharField(blank=True, choices=[('not_started', '待开始'), ('in_progress', '进行中'), ('completed_pending', '已完成待部署'), ('deployed', '已部署')], max_length=24, verbose_name='建站进度'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tech_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_assigned_deal_customers', to=settings.AUTH_USER_MODEL, verbose_name='承接技术'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='consultant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='咨询师'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='contract_entity',
            field=models.CharField(blank=True, help_text='成交时确定的合同签约主体(一般=公司名)', max_length=128, verbose_name='签约主体'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='deal_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='成交时间'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='deal_business',
            field=models.CharField(blank=True, max_length=128, verbose_name='成交业务'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='is_invoiced',
            field=models.BooleanField(default=False, verbose_name='是否开票'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='is_tax_included',
            field=models.BooleanField(default=False, verbose_name='是否含税'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='sales',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='成交销售'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='site_category',
            field=models.CharField(blank=True, choices=[('ICP', 'ICP许可证'), ('EDI', 'EDI许可证'), ('ICPEDI', 'ICPEDI（组合套餐）'), ('corp_site', '企业官网'), ('corp_site_icp', '企业官网+备案'), ('app', 'APP/小程序'), ('other', '其他')], max_length=24, verbose_name='建站类目'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='site_contact_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='网站联系地址'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='site_contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='网站联系邮箱'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='site_contact_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='网站联系电话'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='site_domain_icp',
            field=models.TextField(blank=True, verbose_name='域名与备案'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='site_full_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='网站全称'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='site_info',
            field=models.TextField(blank=True, verbose_name='网站搭建信息'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='site_progress',
            field=models.CharField(blank=True, choices=[('not_started', '待开始'), ('in_progress', '进行中'), ('completed_pending', '已完成待部署'), ('deployed', '已部署')], max_length=24, verbose_name='建站进度'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='tech_assigned',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='承接技术'),
        ),
    ]
