# Generated by Django 5.2.16 on 2026-09-02

from django.db import migrations


def merge_project_into_customers(apps, schema_editor):
    """一表化(老板 09-02 拍板:补字段不建表):5 个项目数据并入对应成交客户(0022 新字段).

    客户自身字段(公司名/联系人/电话/来源/报价)已是唯一源,不做快照覆盖;
    只补项目表独有字段:成交业务/签约/开票/建站/站点/进度/承接技术/成交时间/销售/咨询师.
    同时清理老板随手乱填的测试数据(阿斯顿撒旦)."""
    Customer = apps.get_model("customers", "Customer")
    Project = apps.get_model("projects", "Project")
    ProjectPayment = apps.get_model("projects", "ProjectPayment")
    ProjectExpense = apps.get_model("projects", "ProjectExpense")
    COPIED = [
        "deal_business", "contract_entity", "is_invoiced", "is_tax_included",
        "site_category", "site_info", "site_full_name", "site_domain_icp",
        "site_contact_address", "site_contact_phone", "site_contact_email",
        "site_progress",
    ]
    for p in Project.objects.all():
        c = Customer.objects.filter(pk=p.customer_id).first()
        if not c:
            print(f"[data-migration] 项目{p.pk} 无对应客户,跳过")
            continue
        changed = []
        for f in COPIED:
            v = getattr(p, f)
            if v:
                setattr(c, f, v)
                changed.append(f)
        if p.deal_at and not c.deal_at:
            c.deal_at = p.deal_at
            changed.append("deal_at")
        if p.sales_id and not c.sales_id:
            c.sales_id = p.sales_id
            changed.append("sales")
        if p.consultant_id:
            c.consultant_id = p.consultant_id
            changed.append("consultant")
        if p.tech_assigned_id:
            c.tech_assigned_id = p.tech_assigned_id
            changed.append("tech_assigned")
        if changed:
            c.save(update_fields=changed)
        print(f"[data-migration] 项目{p.pk}->客户{c.pk}: {', '.join(changed) or '无新增'}")

    # 清理垃圾测试数据(老板:随手乱填测试功能的)
    for c in Customer.objects.filter(company__icontains="阿斯顿"):
        for proj in Project.objects.filter(customer=c):
            ProjectPayment.objects.filter(project=proj).delete()
            ProjectExpense.objects.filter(project=proj).delete()
            proj.delete()
        c.delete()
        print(f"[data-migration] 清理垃圾客户: {c.company} pk={c.pk}")


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0022_customer_consultant_customer_contract_entity_and_more"),
    ]

    operations = [
        migrations.RunPython(merge_project_into_customers, migrations.RunPython.noop),
    ]
