# Generated by Django 5.2.16 on 2026-09-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0023_merge_project_into_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pool_type',
            field=models.CharField(blank=True, choices=[('auto', '自动掉入公司客户池'), ('square', '客户池广场（手动释放）')], help_text='30天未跟进自动进公海，或销售手动释放到客户池广场', max_length=16, null=True, verbose_name='公海类型'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('lead', '线索'), ('following', '跟进中'), ('pool', '公司客户池'), ('deal', '已成交'), ('lost', '已流失')], default='lead', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='pool_type',
            field=models.CharField(blank=True, choices=[('auto', '自动掉入公司客户池'), ('square', '客户池广场（手动释放）')], help_text='30天未跟进自动进公海，或销售手动释放到客户池广场', max_length=16, null=True, verbose_name='公海类型'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='status',
            field=models.CharField(choices=[('lead', '线索'), ('following', '跟进中'), ('pool', '公司客户池'), ('deal', '已成交'), ('lost', '已流失')], default='lead', max_length=16, verbose_name='状态'),
        ),
    ]
