# Generated by Django 5.2.16 on 2026-09-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_alter_customer_pool_type_alter_customer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deal_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='实际签约金额,独立于报价金额——报价是销售初始报价,成交总金额是最终确认金额', max_digits=12, null=True, verbose_name='成交总金额'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='deal_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='实际签约金额,独立于报价金额——报价是销售初始报价,成交总金额是最终确认金额', max_digits=12, null=True, verbose_name='成交总金额'),
        ),
    ]
