# Generated by Django 5.2.16 on 2026-09-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0025_add_deal_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='category',
            field=models.CharField(blank=True, help_text="自由填写,如'域名费'/'服务器费'/'技术费'", max_length=64, verbose_name='支出事项'),
        ),
        migrations.AlterField(
            model_name='historicalcost',
            name='category',
            field=models.CharField(blank=True, help_text="自由填写,如'域名费'/'服务器费'/'技术费'", max_length=64, verbose_name='支出事项'),
        ),
    ]
