# Generated by Django 5.2.16 on 2026-09-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0026_cost_category_free_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='qualification_interest',
            field=models.TextField(blank=True, help_text='多项资质需求用符号隔开', verbose_name='资质需求'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='qualification_interest',
            field=models.TextField(blank=True, help_text='多项资质需求用符号隔开', verbose_name='资质需求'),
        ),
    ]
