# Generated by Django 5.2.16 on 2026-09-21 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0028_qualification_list_to_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bad_debt_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='财务专用:确认无法收回的坏账,从待收余额中扣减', max_digits=12, null=True, verbose_name='坏账金额'),
        ),
        migrations.AddField(
            model_name='customer',
            name='reduction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='财务专用:批准的减免,从待收余额中扣减', max_digits=12, null=True, verbose_name='减免金额'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='bad_debt_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='财务专用:确认无法收回的坏账,从待收余额中扣减', max_digits=12, null=True, verbose_name='坏账金额'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='reduction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='财务专用:批准的减免,从待收余额中扣减', max_digits=12, null=True, verbose_name='减免金额'),
        ),
        migrations.AddField(
            model_name='historicalreceipt',
            name='account',
            field=models.CharField(blank=True, help_text="如'珠海金石企服',按每笔收款单独记录", max_length=64, verbose_name='收款账户'),
        ),
        migrations.AddField(
            model_name='historicalreceipt',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认时间'),
        ),
        migrations.AddField(
            model_name='historicalreceipt',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='确认人(财务)'),
        ),
        migrations.AddField(
            model_name='historicalreceipt',
            name='payment_type',
            field=models.CharField(choices=[('deposit', '定金'), ('first', '首期款'), ('middle', '中期款'), ('final', '尾款'), ('other', '其他')], default='other', help_text='定金/首期款/中期款/尾款/其他', max_length=16, verbose_name='款项类型'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='account',
            field=models.CharField(blank=True, help_text="如'珠海金石企服',按每笔收款单独记录", max_length=64, verbose_name='收款账户'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认时间'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_receipts', to=settings.AUTH_USER_MODEL, verbose_name='确认人(财务)'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_type',
            field=models.CharField(choices=[('deposit', '定金'), ('first', '首期款'), ('middle', '中期款'), ('final', '尾款'), ('other', '其他')], default='other', help_text='定金/首期款/中期款/尾款/其他', max_length=16, verbose_name='款项类型'),
        ),
    ]
