# Generated by Django 5.2.16 on 2026-08-20 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_team_lead_alter_user_role_notification_team_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_boss_dashboard', '可看老板总览面板'), ('view_sales_workbench', '可看销售工作台'), ('view_consult_workbench', '可看咨询工作台')], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, help_text='主管可查看本组组员客户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.team', verbose_name='所属团队'),
        ),
    ]
