# Generated by Django 5.2.16 on 2026-08-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_alter_user_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_boss_dashboard', '可看老板总览面板'), ('view_sales_workbench', '可看销售工作台'), ('view_consult_workbench', '可看咨询工作台'), ('view_tech_workbench', '可看技术建站工作台')], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
