# Generated by Django 5.2.16 on 2026-08-28 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='触发人'),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('duplicate', '撞单提醒'), ('assign_customer', '客户分配'), ('deal_convert', '成交立项'), ('project_assign', '咨询分配'), ('cert_progress', '办证进度'), ('cost_apply', '成本申请'), ('cost_review', '成本审核'), ('payment_record', '收款录入'), ('payment_review', '收款审核'), ('site_task', '建站任务'), ('site_taken', '任务承接'), ('site_progress', '建站进度'), ('site_done', '建站完工'), ('site_info', '站点信息'), ('pool_flow', '公海流转'), ('other', '其他')], default='other', max_length=32, verbose_name='事件类型'),
        ),
        migrations.AddField(
            model_name='notification',
            name='entity_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='实体ID'),
        ),
        migrations.AddField(
            model_name='notification',
            name='entity_type',
            field=models.CharField(blank=True, max_length=16, verbose_name='实体类型'),
        ),
        migrations.AddField(
            model_name='notification',
            name='importance',
            field=models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=16, verbose_name='重要程度'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at', '-created_at'], name='notif_recipient_unread'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'importance'], name='notif_recipient_imp'),
        ),
    ]
