# Generated by Django 5.2.16 on 2026-09-02

from django.db import migrations


def grant_sales_customer_perms(apps, schema_editor):
    """销售/销售主管用户授予客户模型权限——老板反馈(09-02):销售侧边栏只有工作台,
    客户管理/成交管理整组不显示。根因:simpleui 菜单按模型权限过滤,销售用户此前只有
    view_sales_workbench 一个权限,customers 模型权限全缺 → 客户相关菜单整组被隐藏."""
    User = apps.get_model("accounts", "User")
    Permission = apps.get_model("auth", "Permission")
    codes = [
        "view_customer", "add_customer", "change_customer",
        "view_customerattachment", "view_receipt", "view_cost",
    ]
    perms = list(Permission.objects.filter(codename__in=codes, content_type__app_label="customers"))
    users = list(User.objects.filter(role__in=["sales", "sales_lead"]))
    n = 0
    for u in users:
        u.user_permissions.add(*perms)
        n += 1
    print(f"[data-migration] 客户权限 {len(perms)} 个 × 销售/组长用户 {n} 个")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_options"),
    ]

    operations = [
        migrations.RunPython(grant_sales_customer_perms, migrations.RunPython.noop),
    ]
