# Generated by Django 5.2.16 on 2026-09-02

from django.db import migrations


def grant_consult_customer_perms(apps, schema_editor):
    """咨询/咨询主管用户授予客户与收支权限——老板反馈(09-02):咨询主管侧边栏只有工作台+通知.

    根因:同销售(0008)——用户此前只有 view_consult_workbench 一个权限,customers 权限全缺,
    simpleui 按模型权限过滤 → 成交管理整组被隐藏。细则:咨询部负责办证跟进/收款支出填写,
    需查看成交客户与其收款/支出(技术部不授,细则:技术看不到客户与财务)."""
    User = apps.get_model("accounts", "User")
    Permission = apps.get_model("auth", "Permission")
    codes = [
        "view_customer",
        "view_receipt", "add_receipt", "change_receipt",
        "view_cost", "add_cost", "change_cost",
    ]
    perms = list(Permission.objects.filter(codename__in=codes, content_type__app_label="customers"))
    users = list(User.objects.filter(role__in=["consultant", "consultant_lead"]))
    n = 0
    for u in users:
        u.user_permissions.add(*perms)
        n += 1
    print(f"[data-migration] 客户/收支权限 {len(perms)} 个 × 咨询/咨询主管用户 {n} 个")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_grant_sales_customer_perms"),
    ]

    operations = [
        migrations.RunPython(grant_consult_customer_perms, migrations.RunPython.noop),
    ]
