# Generated by Django 5.2.16 on 2026-09-04
from django.db import migrations


def grant_consult_lead_sales_workbench(apps, schema_editor):
    """咨询主管授予 view_sales_workbench 权限——老板要求(09-04):咨询主管需看到「客户管理」+「成交管理」菜单组,
    用于查看待分配单子/分配咨询师/管理成交客户进度。0009 已授客户模型权限但未授此菜单权限。"""
    User = apps.get_model("accounts", "User")
    Permission = apps.get_model("auth", "Permission")
    perm = Permission.objects.filter(
        codename="view_sales_workbench", content_type__app_label="accounts"
    ).first()
    if not perm:
        return
    users = list(User.objects.filter(role="consultant_lead"))
    for u in users:
        u.user_permissions.add(perm)
    print(f"[data-migration] view_sales_workbench → 咨询主管 {len(users)} 人")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_grant_consult_customer_perms"),
    ]

    operations = [
        migrations.RunPython(grant_consult_lead_sales_workbench, migrations.RunPython.noop),
    ]
