# Generated by Django 5.2.16 on 2026-09-04
from django.db import migrations


def grant_consult_lead_recycled_customer(apps, schema_editor):
    """咨询主管补授 view_recycledcustomer 权限——0010 授了 view_sales_workbench 但 simpleui 客户管理组
    含回收站(recycledcustomer 模型),缺此模型权限导致整个客户管理菜单组被隐藏。"""
    User = apps.get_model("accounts", "User")
    Permission = apps.get_model("auth", "Permission")
    perm = Permission.objects.filter(
        codename="view_recycledcustomer", content_type__app_label="customers"
    ).first()
    if not perm:
        return
    users = list(User.objects.filter(role="consultant_lead"))
    for u in users:
        u.user_permissions.add(perm)
    print(f"[data-migration] view_recycledcustomer → 咨询主管 {len(users)} 人")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_grant_consult_lead_sales_workbench"),
    ]

    operations = [
        migrations.RunPython(grant_consult_lead_recycled_customer, migrations.RunPython.noop),
    ]
