# Generated by Django 5.2.16 on 2026-09-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_grant_finance_perms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_boss_dashboard', '可看总经办数据总览'), ('view_sales_workbench', '可看销售数据总览'), ('view_consult_workbench', '可看咨询数据总览'), ('view_tech_workbench', '可看技术数据总览'), ('view_finance_workbench', '可看财务管理菜单')], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
